name: Build Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Geode CLI
        uses: geode-sdk/install-geode-cli@main

      - name: Build mod
        shell: bash
        run: |
          geode build --no-install
